package com.fmc.starterApp.models.entity;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents an application user.
 *
 * <p>This entity is mapped to the "users" table and stores essential user information.
 * It represents the data of users that have been imported from Keycloak or managed within the application.
 * Key details include the user's name and email address, both of which are mandatory fields.
 *
 * <p><strong>Key Fields:</strong>
 * <ul>
 *   <li>{@code userId} - The unique identifier for the user, auto-generated by the database.</li>
 *   <li>{@code userName} - The user's name. This field is mandatory and has a maximum length of 50 characters.</li>
 *   <li>{@code email} - The user's email address. This field is mandatory, validated to be in a proper email format,
 *       and has a maximum length of 100 characters.</li>
 *   <li>{@code userTimes} - A list of login logs associated with this user.
 *     <p>Each login event is represented by a {@link UserLogs} entity, which tracks individual login events.
 *     This relationship enables the system to maintain a detailed history of user activity for auditing and monitoring purposes.</p>
 *   </li>
 * </ul>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@Table(name = "users")
public class AppUser {

    /**
     * The unique identifier for the user.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;

    /**
     * The user's name.
     *
     * <p>This field is mandatory, has a maximum length of 50 characters, and represents the user's full name or display name.
     */
    @NonNull
    @Column(nullable = false, length = 50)
    private String userName;

    /**
     * The user's email address.
     *
     * <p>This field is mandatory, validated to conform to a standard email format, has a maximum length of 100 characters,
     * and is critical for user communication and identity verification.
     */
    @NonNull
    @Email(message = "Invalid email address")
    @Column(nullable = false, unique = true, length = 100)
    private String email;

    /**
     * The list of login logs associated with this user.
     *
     * <p>This one-to-many relationship with the {@link UserLogs} entity represents the login events recorded
     * for the user. Each {@link UserLogs} entry tracks a single login event, allowing the system to maintain
     * a detailed history of user activity for auditing and monitoring purposes.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "appUser")
    @JsonManagedReference
    private List<UserLogs> userTimes;
}
