package com.fmc.starterApp.models.entity;

import java.time.LocalDateTime;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents an image associated with a Carver Matrix.
 *
 * <p>This entity is mapped to the "matrix_images" table and stores image-related information
 * for a given Carver Matrix. Each MatrixImage is linked to a specific {@link CarverMatrix} and includes
 * details such as the URL of the image and the timestamp when the image was uploaded.
 *
 * <p><strong>Key Fields:</strong>
 * <ul>
 *   <li>{@code imageId} - The unique identifier for the image, auto-generated by the database.</li>
 *   <li>{@code carverMatrix} - The {@link CarverMatrix} to which this image belongs. This field is mandatory.</li>
 *   <li>{@code imageUrl} - The URL of the image. This field is mandatory, should be a valid URL, and is limited to 500 characters.</li>
 *   <li>{@code uploadedAt} - The timestamp when the image was uploaded. Automatically set to the current timestamp.</li>
 * </ul>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@Table(name = "matrix_images")
public class MatrixImage {

    /**
     * The unique identifier for the image.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long imageId;

    /**
     * The {@link CarverMatrix} to which this image belongs.
     */
    @ManyToOne
    @JoinColumn(name = "matrix_id", nullable = false)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private CarverMatrix carverMatrix;

    @ManyToOne
    @JoinColumn(name = "item_id", nullable = false)
    private CarverItem carverItem;

    /**
     * The URL of the image.
     * <p>This field is mandatory, should be a valid URL, and is limited to 500 characters.</p>
     */
    @NonNull
    @Column(name = "image_url", nullable = false, length = 500)
    private String imageUrl;

    /**
     * The timestamp when the image was uploaded.
     */
    @Column(name = "uploaded_at", columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private LocalDateTime uploadedAt = LocalDateTime.now();
}
